version: '3.1'
services:
  db:
    image: postgres:12.0-alpine
    restart: always
    container_name: blkexplorer-postgres
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
  makemigrations:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - flush
    image: blkexplorer:prod
    container_name: blkexplorer-makemigrations
    command: python manage.py makemigrations --noinput
    env_file:
      - .env
  migrations:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - makemigrations
    image: blkexplorer:prod
    container_name: blkexplorer-migrations
    command: python manage.py migrate --noinput
    env_file:
      - .env
  flush:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - db
    image: blkexplorer:prod
    container_name: blkexplorer-flush
    command: python manage.py flush --no-input
    env_file:
      - .env
  collectstatics:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - nginx
    image: blkexplorer:prod
    container_name: blkexplorer-collectstatics
    command: python manage.py collectstatic --no-input --clear
    env_file:
      - .env
  nginx:
    build: ./nginx
    container_name: nginx-blkexplorer
    volumes:
      - static_volume:/opt/project/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn blkexplorer.wsgi:application --bind 0.0.0.0:8000
    container_name: blkexplorer-gunicorn
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - db
      - migrations
  load:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - db
      - migrations
    image: blkexplorer:prod
    container_name: blkexplorer-update_from_last_block
    command: python manage.py update_from_last_block
    env_file:
      - .env
volumes:
  postgres_data:
  static_volume: