# Generated by Django 2.2.13 on 2020-06-13 16:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import unixtimestampfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ABI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(unique=True)),
                ('label', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
            options={
                'db_table': 'abis',
                'verbose_name_plural': 'ABIs',
                'verbose_name': 'ABI',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(max_length=42, null=True)),
                ('balance_in_wei', models.CharField(db_column='balance_in_wei', default='0', max_length=50, null=True)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', unixtimestampfield.fields.UnixTimeStampField(null=True)),
                ('number', models.IntegerField(db_index=True, null=True)),
                ('hash', models.CharField(max_length=66, null=True)),
                ('mix_hash', models.CharField(max_length=66, null=True)),
                ('difficulty', models.BigIntegerField(null=True)),
                ('gas_limit', models.IntegerField(null=True)),
                ('gas_used', models.IntegerField(null=True)),
                ('state_root', models.CharField(max_length=66, null=True)),
                ('receipts_root', models.CharField(max_length=66, null=True)),
                ('transactions_root', models.CharField(max_length=66, null=True)),
                ('total_difficulty', models.BigIntegerField(null=True)),
                ('size', models.BigIntegerField(null=True)),
                ('nonce', models.CharField(max_length=50, null=True)),
                ('parent_hash', models.CharField(max_length=66, null=True)),
                ('sha3_uncles', models.CharField(max_length=66, null=True)),
                ('miner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ethereum.Account')),
            ],
            options={
                'db_table': 'blocks',
                'verbose_name_plural': 'Blocks',
                'unique_together': {('hash', 'number')},
                'verbose_name': 'Block',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cumulative_gas_used', models.IntegerField(null=True)),
                ('gas_used', models.IntegerField(null=True)),
                ('status', models.IntegerField(null=True)),
                ('transaction_hash', models.CharField(max_length=82, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=82, null=True, unique=True)),
                ('gas_price', models.BigIntegerField(null=True)),
                ('gas', models.IntegerField(null=True)),
                ('input', models.TextField(null=True)),
                ('transaction_index', models.IntegerField(null=True)),
                ('nonce', models.IntegerField(null=True)),
                ('value', models.BigIntegerField(null=True)),
            ],
            options={
                'db_table': 'transactions',
                'verbose_name_plural': 'Transactions',
                'verbose_name': 'Transaction',
            },
        ),
        migrations.CreateModel(
            name='TransactionRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ethereum.Block')),
                ('from_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to='ethereum.Account')),
                ('receipt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ethereum.Receipt')),
                ('to_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to='ethereum.Account')),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='ethereum.Transaction')),
            ],
            options={
                'db_table': 'transaction_relationships',
                'verbose_name_plural': 'TX - Account relations',
                'unique_together': {('from_account', 'to_account', 'transaction')},
                'verbose_name': 'TX - Account relation',
            },
        ),
        migrations.CreateModel(
            name='SmartContract',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ethereum.Account')),
                ('abi', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ethereum.ABI')),
                ('deploy_tx', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ethereum.TransactionRelationship')),
                ('deployer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smart_contracts', to='ethereum.Account')),
            ],
            options={
                'db_table': 'smart_contracts',
                'verbose_name_plural': 'Smart Contracts',
                'verbose_name': 'Smart Contract',
            },
            bases=('ethereum.account',),
        ),
    ]
