# Generated by Django 2.1.2 on 2019-02-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethereum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance_in_gwei',
            field=models.BigIntegerField(db_column='balance_in_gwei', default=0),
        ),
    ]
