# Generated by Django 2.1.2 on 2019-03-23 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ethereum', '0002_account_balance_in_gwei'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(null=True)),
                ('block_number', models.IntegerField(null=True)),
                ('hash', models.CharField(max_length=80, null=True)),
            ],
            options={
                'verbose_name': 'Block',
                'verbose_name_plural': 'Blocks',
                'db_table': 'blocks',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ethereum.Block')),
            ],
            options={
                'verbose_name': 'TX - Account relation',
                'verbose_name_plural': 'TX - Account relations',
                'db_table': 'transaction_relationships',
            },
        ),
        migrations.RemoveField(
            model_name='accounttransactionrelation',
            name='from_account',
        ),
        migrations.RemoveField(
            model_name='accounttransactionrelation',
            name='to_account',
        ),
        migrations.RemoveField(
            model_name='accounttransactionrelation',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='tx_hash',
        ),
        migrations.AddField(
            model_name='transaction',
            name='gas',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='gas_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='hash',
            field=models.CharField(max_length=82, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='input',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='nonce',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_index',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='value',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance_in_gwei',
            field=models.BigIntegerField(db_column='balance_in_gwei', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='public_key',
            field=models.CharField(max_length=42, null=True),
        ),
        migrations.DeleteModel(
            name='AccountTransactionRelation',
        ),
        migrations.AddField(
            model_name='transactionrelationship',
            name='from_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_account', to='ethereum.Account'),
        ),
        migrations.AddField(
            model_name='transactionrelationship',
            name='receipt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ethereum.Receipt'),
        ),
        migrations.AddField(
            model_name='transactionrelationship',
            name='to_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_account', to='ethereum.Account'),
        ),
        migrations.AddField(
            model_name='transactionrelationship',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ethereum.Transaction'),
        ),
        migrations.AlterUniqueTogether(
            name='transactionrelationship',
            unique_together={('from_account', 'to_account', 'transaction')},
        ),
    ]
