# Generated by Django 2.1.2 on 2019-03-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethereum', '0003_auto_20190323_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='gas_price',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='value',
            field=models.BigIntegerField(null=True),
        ),
    ]
