# Generated by Django 2.1.2 on 2019-03-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethereum', '0004_auto_20190323_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='number',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.RemoveField(
            model_name='block',
            name='block_number',
        ),
        migrations.AlterUniqueTogether(
            name='block',
            unique_together={('hash', 'number')},
        ),
    ]
