# Generated by Django 2.1.2 on 2019-03-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethereum', '0005_auto_20190323_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='difficulty',
            field=models.BigIntegerField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='gas_limit',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='gas_used',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='mix_hash',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='receipt_root',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='size',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='state_root',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='total_difficulty',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='transactions_root',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
