# Generated by Django 2.1.2 on 2019-03-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethereum', '0006_auto_20190323_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='difficulty',
            field=models.BigIntegerField(null=True),
        ),
    ]
